version: '3'
services:
  hbase-master:
    image: exstock/hbase:1.2.2
    container_name: hbase-master
    ports:
      - "50070:50070"
      - "8088:8088"
      - "8080:8080"
      - "8042:8042"
      - "16010:16010"
    volumes:
      - "./volume/hbase/master:/hworks/"
      - "./volume/hbase/logs/master:/root/hbase/logs/"
      - "./volume/works/hadoop/dfs/namenode:/works/hadoop/dfs/namenode"
      - "./volume/works/hadoop/dfs/datanode:/works/hadoop/dfs/datanode"
      - "./volume/works/hadoop/dfs/namesecondary:/works/hadoop/dfs/namesecondary"
      - "./volume/works/hadoop/tmp:/works/hadoop/tmp"
      - "./volume/works/hadoop/logs:/root/hadoop/logs"
      - "./volume/works/spark/logs:/root/spark/logs/"
      - "./volume/works/hive/logs:/root/hive/logs/"
      - "./volume/works/zookeeper/logs:/root/zookeeper/logs/"
      - "./volume/code:/code"
    hostname: data-warehouse
    networks:
      hadoop-docker:
        aliases: 
          - hbase-master
    tty: true

  mysql:
    image: mysql:5.7
    volumes:
      - "./volume/mysql:/var/lib/mysql"
    container_name: mysql
    hostname: data-warehouse
    networks:
      - hadoop-docker
    environment:
      - MYSQL_ROOT_PASSWORD=hadoop
    tty: true
  
  zoo1:
    image: twinsen/zookeeper:3.4.8
    volumes:
      - "./volume/zk/zoo1:/works"
    container_name: zoo1
    hostname: data-warehouse
    networks:
      hadoop-docker:
        aliases: 
          - zoo1
    tty: true
    
networks:
  hadoop-docker:
    external: true